version: '3.9'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hotel
      HOST_AUTH_METHOD: trust
      volumes:
        -db-volume:/var/lib/postgresql/data
  adminer:
   image: adminer
   restart: always
volumes:
  db-volume: